CREATE TABLE PRESCRIZIONE (
NUM_PRESCRIZIONE NUMBER(3) PRIMARY KEY NOT NULL,
DATA_PRESCRIZIONE DATE,
ASSE_SX NUMBER,
ASSE_DX NUMBER,
SFERO_SX NUMBER,
SFERO_DX NUMBER,
CILINDRO_SX NUMBER,
CILINDRO_DX NUMBER,
DURATA_PRESCRIZIONE NUMBER,
DISTANZA_INTERPUPILLARE NUMBER,
SEMIDAV NUMBER,
DISTANZA_APICE_CORNEALE NUMBER,
ANGOLO_PANTOSCOPICO NUMBER,
INSET NUMBER,
TIPO_LENTE VARCHAR2(25),
TRATTAMENTO VARCHAR2(16)
);

CREATE TABLE MEDICO(
CF CHAR(16) PRIMARY KEY NOT NULL,
SPECIALIZZAZIONE VARCHAR2(30),
ANNI_ESP NUMBER
);

CREATE TABLE PRESCIVE(
CF_MED CHAR(16) NOT NULL,
NUM_PRESCRIZIONE  NUMBER(3) NOT NULL,
CONSTRAINT MED
        FOREIGN KEY (CF_MED)
        REFERENCES MEDICO(CF),
CONSTRAINT PRESC
        FOREIGN KEY (NUM_PRESCRIZIONE)
        REFERENCES PRESCRIZIONE(NUM_PRESCRIZIONE)
);